In [1]:
import numpy as np
students = np.random.randint(50,101,size=(50,5))
students

array([[ 66,  66,  70,  75,  80],
       [ 59,  71,  64,  60,  88],
       [ 76,  64,  63,  98,  86],
       [ 77,  80,  99,  89,  79],
       [ 78,  64,  51,  75,  80],
       [ 93,  51,  75,  86,  81],
       [ 71,  74,  95,  63,  55],
       [ 98,  63,  68,  88,  75],
       [ 62,  75,  52,  87,  84],
       [ 64,  56,  81, 100,  58],
       [ 85,  93,  74,  89,  62],
       [ 77,  84,  87,  92,  70],
       [ 68,  72,  70,  98,  95],
       [ 57,  94,  80,  62,  86],
       [ 65,  56,  94,  59,  86],
       [ 76,  93,  99,  75,  74],
       [ 84,  83,  60,  86,  94],
       [ 65,  83,  50,  71,  62],
       [ 89,  60,  75,  75,  69],
       [ 97,  91,  68,  97,  73],
       [ 91,  99,  72,  55,  55],
       [ 66,  97,  86,  95,  80],
       [ 63,  91,  98,  59,  70],
       [ 66,  89,  96,  95,  66],
       [ 50,  52,  99,  81,  53],
       [ 85,  54,  82,  62,  68],
       [ 82,  50,  85,  88,  89],
       [ 87,  93,  88,  90,  72],
       [ 68,  65,  55,  91,  81],
       [ 96,  

In [2]:
students[0,0]
students[:1,:]
students[:1] #前一個學生
students[:2] #前2個學生
students[-5:] #最後5個學生

array([[81, 61, 67, 78, 92],
       [94, 50, 69, 80, 71],
       [54, 54, 76, 81, 60],
       [59, 64, 67, 63, 63],
       [65, 66, 78, 57, 92]])

In [3]:
students[:,0] #第一科所有分數
students[:,-1] #最後一科所有分數

array([80, 88, 86, 79, 80, 81, 55, 75, 84, 58, 62, 70, 95, 86, 86, 74, 94,
       62, 69, 73, 55, 80, 70, 66, 53, 68, 89, 72, 81, 60, 85, 69, 72, 77,
       93, 63, 76, 88, 86, 64, 67, 51, 87, 73, 63, 92, 71, 60, 63, 92])

In [4]:
np.sum(students[:1]) #第一個學生總分
np.sum(students[:2],axis=1) #前2個學生的總分 
np.sum(students,axis=1) #全班每位學生的總分
np.mean(students,axis=0) #每一科全班的平均
np.median(students,axis=0) #每一科全班的中位數

array([76.5, 72.5, 75. , 79.5, 73.5])